export const titulos = {
  0: [
    'Nome',
    'Nascimento',
    'CEP',
    'Endereço',
    'Bairro',
    'Cidade',
    'UF',
    'Telefone',
    'Sexo',
    'Profissão',
  ],
  1: [
    'Atividade Física',
    'Qual?',
    'Tipo de calçado mais usado',
    'Alérgico',
    'Qual?',
    'Familiares Diabético',
    'Grau de parentesco?',
    'Hipertenso',
    'Diabético',
    'Grávida ou Lactante (Amamentando)',
  ],
  2: [
    'Unha encravada',
    'Micose na unha',
    'Micose Plantar (pés)',
    'Unha descolada',
    'Manchas nas unhas',
    'Bromidrose (chulé)',
    'Sudorese',
    'Psoríase',
    'Onicocriptose (unha encravada)',
    'Onicomicose (fungo na unha)',
    'Onicogrifose (unha grossa)',
    'Onicofose (unha fina)',
    'Onicorrexe (unha quebradiça)',
    'Onicose (unha fraca)',
    'Onicólise (descolamento da unha)',
  ],
  3: [
    'Cadeirante',
    'Muleta',
    'Andador',
    'Bengala',
    'Acamado',
    'Atendimento Domiciliar',
  ],
  4: [
    'Dedos em Garra',
    'Joanete',
    'Dedos em Martelo',
    'Amputações',
    'Edema (inchaço nas pernas)',
  ],
};
